### ISSUE TITLE
ADS error 1861

### ISSUE THREAD

**Issue by Ramgopalcr** [Beckhoff/ADS#56] opened 2018-02-01 16:08 UTC
Hi, 

I'm using the lib with the example file and after adding the static route and it does appear in the target and the client routes.

But I still get the timeout error, If I just use the standard block ADS read and call for the same index, it does read from the target PC.

Not sure, what can I check 

Thanks,
Ram

**Comment by pbruenn** [comment] 2018-02-02 07:37
Seems to be a duplicate of #14

**Closed by pbruenn** 2018-02-02 07:37 UTC
